name: burhanudeen_abdullah

on: 
  push: 
    branches: ["main"]



jobs:
  build:
  
    runs-on: ubuntu-latest
    steps: 
       
      - uses: actions/checkout@v4

      - name: trying to update my machine
        run: sudo apt-get update

      - name: install nginx 
        run: sudo apt-get install nginx 

      - name: sudo systemctl start nginx
        run: sudo systemctl start nginx

      - name: going to check the status of nginx
        run: sudo nginx -t 

      - name: install ufw
        run: sudo apt-get install ufw

      - name: sudo ufw allow 'Nginx Full'
        run: sudo ufw allow 80/tcp

      - name: cd into the root directory
        run: cd /var/www/html
      
      - name: create a file
        run: echo "Hello World" > index.html

      - name: change file mode
        run: sudo chmod 777 index.html
      
      - name: am going to upload the file to the server
        use: actions/upload-artifact@v4
        with:
          name: index.html
          path: /var/www/html/index.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download the file
        uses: actions/download-artifact@v4
        with:
          name: index.html
          path: /var/www/html/index.html

      - name: cat the file
        run: cat index.html
        
 
    
    